### ISSUE TITLE
Sometimes jshint just fails

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-example-app#38]
e.g.

```

/Users/davida/src/newbuild2/node_modules/jshint-jsx/node_modules/jshint/src/jshint.js:5264
    globals = Object.keys(scope);
                     ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Function.itself.data (/Users/davida/src/newbuild2/node_modules/jshint-jsx/node_modules/jshint/src/jshint.js:5264:22)
    at reportErrors (/Users/davida/src/newbuild2/node_modules/gulp-jshint/src/lint.js:35:24)
    at /Users/davida/src/newbuild2/node_modules/gulp-jshint/src/lint.js:74:25
    at respond (/Users/davida/src/newbuild2/node_modules/gulp-jshint/node_modules/rcloader/index.js:68:7)
    at respond (/Users/davida/src/newbuild2/node_modules/gulp-jshint/node_modules/rcloader/node_modules/rcfinder/index.js:140:7)
    at /Users/davida/src/newbuild2/node_modules/gulp-jshint/node_modules/rcloader/node_modules/rcfinder/index.js:124:17
    at /Users/davida/src/newbuild2/node_modules/gulp-jshint/node_modules/rcloader/node_modules/rcfinder/index.js:77:13
    at process._tickCallback (node.js:442:13)
```

Not sure how to debug this.

**Comment by Pomax** [comment]
if you can isolate where this happens with some tactical block commenting, it'll be good to document what can cause this kind of error.

**Comment by Pomax** [comment]
https://github.com/MozillaFoundation/mofo-example-app/issues/39 will be relevant here
